// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwK4KZojJs9s0hAc1W-_6W60cFVYHOc-4',
    appId: '1:174841766591:web:e61f795b436f6cacbe1c0a',
    messagingSenderId: '174841766591',
    projectId: 'innoxdev',
    authDomain: 'innoxdev.firebaseapp.com',
    storageBucket: 'innoxdev.appspot.com',
    measurementId: 'G-8TMWKVBVTK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgK4fVGH-nVgvh2pzB7CvoIT9o0aiPxko',
    appId: '1:174841766591:android:11c7fe0588e36c3abe1c0a',
    messagingSenderId: '174841766591',
    projectId: 'innoxdev',
    storageBucket: 'innoxdev.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD11lZgsijZD-dPEi4LNItIOm9OemsiTWI',
    appId: '1:174841766591:ios:c215209ce140b95dbe1c0a',
    messagingSenderId: '174841766591',
    projectId: 'innoxdev',
    storageBucket: 'innoxdev.appspot.com',
    iosClientId: '174841766591-1rptmvfc8t7q7bnaabon48pd9bpbhirj.apps.googleusercontent.com',
    iosBundleId: 'dev.innox.demeter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD11lZgsijZD-dPEi4LNItIOm9OemsiTWI',
    appId: '1:174841766591:ios:15bce202e5172dd2be1c0a',
    messagingSenderId: '174841766591',
    projectId: 'innoxdev',
    storageBucket: 'innoxdev.appspot.com',
    iosClientId: '174841766591-h67fpc59thim1dgtsf71sj2ou1t19nog.apps.googleusercontent.com',
    iosBundleId: 'dev.innox.demeter.RunnerTests',
  );
}
